### ISSUE TITLE
Sample templates generated by webstorm is not working.

### ISSUE THREAD

**Issue by sureshg** [google/stagehand#379] opened 2017-03-16 07:32 UTC
The sample webapp created using webstrom dart templates are not working. By default it couldn't able to find the `dart.js` path `  <script defer src="packages/browser/dart.js"></script>` and it seems the document location rewrite in `index.html` causing the issues.

## Version information

- `IDEA WS-171.3780.41`
- `1.23.0-dev.7.0`
- `WS-171.3780.41, JRE 1.8.0_112-release-736-b10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.3 unknown, screens 1440x900  Retina`

#
![dart-issue](https://cloud.githubusercontent.com/assets/356994/23985983/14aeee7c-09df-11e7-8215-efb8648c7fad.gif)

**Comment by chalin** [comment] 2017-03-16 13:21
Hi. Likely a duplicate of #374, which has been fixed but not released yet. In the meantime you can either:
- Avoid using hyphens in project names, or
- Fix the `<script>` in `index.html`: replace the underscore in the regex with a dash (see #376).

**Closed by chalin** 2017-03-16 13:21 UTC

**Comment by kwalrath** [comment] 2017-03-16 21:21
The template has been updated. Restarting your IDE should pick up the new templates.
